### ISSUE TITLE
VERITAS limit differ from the one produced with gLike

### ISSUE THREAD

**Issue by TjarkMiener** [TjarkMiener/likelihood_combiner#11]
All limits overlay pretty smoothly with the ones produced with [gLike](https://github.com/javierrico/gLike), except the VERITAS limits. Maybe different input files are used or gLike is processing these files different than the lklcom.

**Comment by tjarkmiener** [comment]
closed by https://github.com/TjarkMiener/likelihood_combiner/commit/8f218fdc5740b056954a08e2e9d6a9c4d2c9c082
