### ISSUE TITLE
Bug in the plot with collaborations

### ISSUE THREAD

**Issue by TjarkMiener** [TjarkMiener/likelihood_combiner#7]
It seems that the plot with collaborations is not right. However, the plot with sources looks correct.

**Comment by tjarkmiener** [comment]
Current master can't plot limits from combined sources from one collaboration. However, this plot would be nice to add.

**Comment by tjarkmiener** [comment]
Workaround: Select in the config files under "Configuration/collaborations" only one collaboration and plot them together with the combination of all collaborations using a separate script.

**Comment by tjarkmiener** [comment]
Add this script to a new folder "scripts".
